03-lection1/01-button solution was added
js-tasks-ru/htmlcss-20211125_alexandr-nikulin pull request #3
Opened 2021-12-16 10:11 UTC by avn

please check my solution

2021-12-16 10:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-16 10:24 UTC, GSemikozov requested changes

2021-12-16 10:24 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
еще нужно указать какой font-family используется

2021-12-16 10:24 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
чтобы пользователь не мог нажать на disabled - pointer-events: none

2021-12-16 10:24 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: none;
лучше сбросить на уровне блока

2021-12-16 10:24 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    --hover-background: var(--hover-primary);
переменные - если они тут же применяются и больше нигде не переиспользуются - лучше тогда и не использовать)

2021-12-16 10:24 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    box-shadow: none;
общий сброс лучше добавить сразу на уровне блока

2021-12-16 10:24 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background: white;
цвет возьмем из переменных

2021-12-17 12:50 UTC, avn commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
сделал

2021-12-17 12:51 UTC, avn commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
сделал

2021-12-17 12:51 UTC, avn commented on 03-lection1/01-button/button.css
> +    border: none;
сделал

2021-12-17 12:51 UTC, avn commented on 03-lection1/01-button/button.css
> +    --hover-background: var(--hover-primary);
сделал

2021-12-17 12:51 UTC, avn commented on 03-lection1/01-button/button.css
> +    box-shadow: none;
сделал

2021-12-17 12:51 UTC, avn commented on 03-lection1/01-button/button.css
> +    background: white;
сделал

2021-12-17 20:17 UTC, GSemikozov approved these changes

2021-12-17 20:17 UTC, merged