03-lection1/02-accordion solution was added
js-tasks-ru/htmlcss-20211125_alexandr-nikulin pull request #4
Opened 2021-12-16 10:13 UTC by avn

please check my solution

2021-12-16 10:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-16 10:26 UTC, GSemikozov requested changes

2021-12-16 10:26 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border: 1px solid #ACB5BD;
цвет возьмем из переменных

2021-12-16 10:26 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    display: inline;
скорее block?

2021-12-16 10:26 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    font-family: Inter, serif;
а где подключен сам Inter?)

2021-12-16 10:26 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: -8px var(--accordion-left-rigth-margin) 32px var(--accordion-left-rigth-margin);
здесь нет смысла использовать переменные, они только запутывают. Если их нигде не переиспользуем - значит лучше просто сразу значение указать. Кстати, а зачем отрицательный марджин?

2021-12-17 12:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-17 13:10 UTC, avn commented on 03-lection1/02-accordion/accordion.css
> +    border: 1px solid #ACB5BD;
сделал

2021-12-17 13:10 UTC, avn commented on 03-lection1/02-accordion/accordion.css
> +    display: inline;
сделал

2021-12-17 13:10 UTC, avn commented on 03-lection1/02-accordion/accordion.css
> +    font-family: Inter, serif;
добав в font.css

2021-12-17 13:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-17 13:13 UTC, avn commented on 03-lection1/02-accordion/accordion.css
> +    margin: -8px var(--accordion-left-rigth-margin) 32px var(--accordion-left-rigth-margin);
переменные - ок, сделал. 
отрицательный маргин - я хотел добаться 16px между summary и details, если это не бест практис, то ок, я могу предложить еще другой вариант, через селектор с [open] убираю margin margin-bottom в 0 у верхнего элемента.

`.accordion__item[open] .accordion__summary {
    margin-bottom: 0;
}`

Подскажите, как лучше?

2021-12-17 20:18 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: -8px var(--accordion-left-rigth-margin) 32px var(--accordion-left-rigth-margin);
да, второй вариант однозначно будет лучше

2021-12-19 21:04 UTC, GSemikozov approved these changes

2021-12-19 21:04 UTC, merged